print("Devops enjineering practice       credits - 3")
print("SPM       credits - 3")
print("Career skills        credits - 3")
print("Communication       credits - 3")
print("HPC       credits - 4")
print("Environment       credits - 3")
print("Undergrad       credits - 1")
print("Seminar       credits - 1")
print("Capstone design     credits -  1")
